sudo: false
bundler_args: --without development
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.0
  - jruby-head
  - rbx-2
  - ruby-head
gemfile:
  - Gemfile
  - Gemfile-0.7.rb
  - Gemfile-0.8.rb
  - Gemfile-0.9.rb
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
